version: '3'

services: 
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes: 
            - ./src:/var/www/app
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
        networks: 
            - laravel

    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: laravel_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel
    
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        ports: 
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        depends_on: 
            - redis
            - mysql
        networks: 
            - laravel

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel
    react:
        build:
            context: .
            dockerfile: Dockerfile.react
        container_name: react
        restart: unless-stopped
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ./neustadt_front:/app
        networks:
            - laravel
            
networks: 
    laravel:
        driver: bridge

volumes:
  node_modules: {}