FROM node:20-alpine

WORKDIR /app

COPY /neustadt_front/package.json ./
COPY /neustadt_front/package-lock.json ./
RUN npm install

COPY neustadt_front/ ./

EXPOSE 3000

CMD [ -d "node_modules" ] && npm start || npm ci && npm start
